export const defaultMenu = {
  banner: "Menú diario 9€ con bebida",
  days: [
    {
      id: "lunes",
      title: "Lunes",
      first: "Sopa de pollo / Macarrones",
      second: "Pollo plancha / Merluza",
      dessert: "Flan / Fruta",
    },
    {
      id: "martes",
      title: "Martes",
      first: "Ensaladilla / Arroz 3 delicias",
      second: "Lomo en salsa / Pescado frito",
      dessert: "Yogur / Fruta",
    },
    {
      id: "miercoles",
      title: "Miércoles",
      first: "Gazpacho / Pasta boloñesa",
      second: "Pechuga empanada / Bacalao",
      dessert: "Natillas / Fruta",
    },
    {
      id: "jueves",
      title: "Jueves",
      first: "Puré de verduras / Ensalada campera",
      second: "Albóndigas / Calamares",
      dessert: "Flan / Yogur",
    },
    {
      id: "viernes",
      title: "Viernes",
      first: "Sopa marisco / Espaguetis",
      second: "Carne mechada / Merluza plancha",
      dessert: "Tarta / Fruta",
    },
    {
      id: "sabado",
      title: "Sábado",
      first: "Paella / Salmorejo",
      second: "Chuleta de cerdo / Pescado del día",
      dessert: "Natillas / Yogur",
    },
  ],
  combosTitle: "Platos combinados",
  combos: [
    "Huevos fritos + patatas + chorizo",
    "Pechuga plancha + ensalada",
    "Lomo + huevo + patatas",
    "Tortilla francesa + ensalada",
    "Hamburguesa + patatas",
  ],
};
